/**
 * Quoted Game — Gerçek Film Replikleri Veritabanı
 *
 * Her replik birebir orijinal filmden alınmıştır.
 * generate-puzzles Edge Function bu veritabanını kullanarak
 * günlük Quoted bulmacaları üretir.
 *
 * Hard Rule: movieQuotes.ts DONMUŞTUR — yeni replikler BURAYA eklenir.
 */

export interface QuotedGameItem {
  id: string;
  movie: string;
  year: number;
  genre: string;
  originalQuote: string;
  fallbackParaphrase: string;
  contextHint: string;
  hints: {
    character: string;
    actor: string;
    director: string;
  };
}

export const QUOTED_DATABASE: QuotedGameItem[] = [
  {
    id: 'q_001',
    movie: 'The Godfather',
    year: 1972,
    genre: 'Suç / Drama',
    originalQuote: "I'm gonna make him an offer he can't refuse.",
    fallbackParaphrase: 'I will present him with a proposition that leaves no room for rejection.',
    contextHint: "70'lerin başında geçen, aile içi güç dengelerini ve mafya dünyasını işleyen bir Amerikan draması.",
    hints: { character: 'Vito Corleone', actor: 'Marlon Brando', director: 'Francis Ford Coppola' },
  },
  {
    id: 'q_002',
    movie: 'Star Wars: Episode V - The Empire Strikes Back',
    year: 1980,
    genre: 'Bilim Kurgu / Macera',
    originalQuote: 'No, I am your father.',
    fallbackParaphrase: 'Incorrect, I am actually your biological parent.',
    contextHint: "80'ler bilim kurgu efsanesi; galaktik bir savaşın tam ortasında geçen büyük bir aile ifşası.",
    hints: { character: 'Darth Vader', actor: 'James Earl Jones (Ses)', director: 'Irvin Kershner' },
  },
  {
    id: 'q_003',
    movie: 'Casablanca',
    year: 1942,
    genre: 'Romantik / Drama',
    originalQuote: "Here's looking at you, kid.",
    fallbackParaphrase: 'This toast is dedicated entirely to you, my dear.',
    contextHint: "2. Dünya Savaşı sırasında Kuzey Afrika'da geçen, aşk ve fedakarlık temalı siyah-beyaz bir klasik.",
    hints: { character: 'Rick Blaine', actor: 'Humphrey Bogart', director: 'Michael Curtiz' },
  },
  {
    id: 'q_004',
    movie: 'The Wizard of Oz',
    year: 1939,
    genre: 'Fantastik / Müzikal',
    originalQuote: "There's no place like home.",
    fallbackParaphrase: "No location in existence can ever match one's own residence.",
    contextHint: 'Ailesinden uzakta, rengarenk fantastik bir dünyada kaybolan genç bir kızın özlemi.',
    hints: { character: 'Dorothy Gale', actor: 'Judy Garland', director: 'Victor Fleming' },
  },
  {
    id: 'q_005',
    movie: 'Scarface',
    year: 1983,
    genre: 'Suç / Aksiyon',
    originalQuote: 'Say hello to my little friend!',
    fallbackParaphrase: 'Greet this small companion of mine!',
    contextHint: "80'ler Miami'sinde bir göçmenin mafya imparatorluğu kurmasını anlatan bir suç destanı.",
    hints: { character: 'Tony Montana', actor: 'Al Pacino', director: 'Brian De Palma' },
  },
  {
    id: 'q_006',
    movie: 'Fight Club',
    year: 1999,
    genre: 'Drama / Psikolojik Thriller',
    originalQuote: 'The first rule of Fight Club is: You do not talk about Fight Club.',
    fallbackParaphrase: 'The primary regulation of our underground gathering is total silence regarding its existence.',
    contextHint: "90'ların sonundan modern tüketim kültürünü ve erkeklik krizini eleştiren karanlık bir kült eser.",
    hints: { character: 'Tyler Durden', actor: 'Brad Pitt', director: 'David Fincher' },
  },
  {
    id: 'q_007',
    movie: 'The Dark Knight',
    year: 2008,
    genre: 'Aksiyon / Çizgi Roman',
    originalQuote: 'Why so serious?',
    fallbackParaphrase: 'What is the cause of such extreme somberness?',
    contextHint: "Kaos ve düzen arasındaki ince çizgiyi sorgulayan 2000'lerin en ikonik çizgi roman uyarlaması.",
    hints: { character: 'Joker', actor: 'Heath Ledger', director: 'Christopher Nolan' },
  },
  {
    id: 'q_008',
    movie: 'Pulp Fiction',
    year: 1994,
    genre: 'Suç / Bağımsız',
    originalQuote: "Say 'what' again. I dare you, I double dare you motherfucker!",
    fallbackParaphrase: 'Repeat that interrogative word once more, I challenge you to do so!',
    contextHint: "Doğrusal olmayan kurgusu ve diyaloglarıyla bilinen 90'lar bağımsız sinema devrimi.",
    hints: { character: 'Jules Winnfield', actor: 'Samuel L. Jackson', director: 'Quentin Tarantino' },
  },
  {
    id: 'q_009',
    movie: 'The Matrix',
    year: 1999,
    genre: 'Bilim Kurgu / Aksiyon',
    originalQuote: "You take the blue pill, the story ends. You take the red pill, you stay in Wonderland.",
    fallbackParaphrase: "Choose the first capsule to return to normalcy, or select the second to discover reality's depths.",
    contextHint: "Gerçekliğin bir simülasyondan ibaret olduğunu savunan çığır açıcı 90'lar bilim kurgusu.",
    hints: { character: 'Morpheus', actor: 'Laurence Fishburne', director: 'Lana & Lilly Wachowski' },
  },
  {
    id: 'q_010',
    movie: 'Forrest Gump',
    year: 1994,
    genre: 'Drama / Romantik',
    originalQuote: "Life was like a box of chocolates. You never know what you're gonna get.",
    fallbackParaphrase: 'Existence resembles an assortment of sweets; the exact outcome is always unpredictable.',
    contextHint: 'Saf bir adamın gözünden Amerikan tarihinin dönüm noktalarını anlatan dokunaklı bir film.',
    hints: { character: 'Forrest Gump', actor: 'Tom Hanks', director: 'Robert Zemeckis' },
  },
  {
    id: 'q_011',
    movie: 'The Sixth Sense',
    year: 1999,
    genre: 'Gerilim / Gizem',
    originalQuote: 'I see dead people.',
    fallbackParaphrase: 'Deceased individuals are visible to my eyes.',
    contextHint: "Çocuk bir hastanın sıra dışı algılarını konu alan, sürpriz sonlu bir 90'lar sonu gerilimi.",
    hints: { character: 'Cole Sear', actor: 'Haley Joel Osment', director: 'M. Night Shyamalan' },
  },
  {
    id: 'q_012',
    movie: 'The Silence of the Lambs',
    year: 1991,
    genre: 'Suç / Psikolojik Gerilim',
    originalQuote: 'A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.',
    fallbackParaphrase: 'An official surveyor attempted to evaluate me once, so I consumed his organs with legumes and red wine.',
    contextHint: 'Genç bir FBI ajanının seri katili yakalamak için dahi bir yamyamdan yardım aldığı psikolojik gerilim.',
    hints: { character: 'Dr. Hannibal Lecter', actor: 'Anthony Hopkins', director: 'Jonathan Demme' },
  },
  {
    id: 'q_013',
    movie: 'The Shining',
    year: 1980,
    genre: 'Korku / Psikolojik',
    originalQuote: "Here's Johnny!",
    fallbackParaphrase: 'Look who has just arrived through the doorway!',
    contextHint: 'Kışın kapalı kalan ıssız bir otelde akıl sağlığını yitiren bir yazarın hikayesi.',
    hints: { character: 'Jack Torrance', actor: 'Jack Nicholson', director: 'Stanley Kubrick' },
  },
  {
    id: 'q_014',
    movie: 'Taxi Driver',
    year: 1976,
    genre: 'Drama / Psikolojik Suç',
    originalQuote: "You talkin' to me?",
    fallbackParaphrase: 'Are those words directed toward my presence?',
    contextHint: "70'ler New York'unun yozlaşmış sokaklarında uykusuzluk çeken ve yalnızlaşan bir adamın hezeyanları.",
    hints: { character: 'Travis Bickle', actor: 'Robert De Niro', director: 'Martin Scorsese' },
  },
  {
    id: 'q_015',
    movie: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 2001,
    genre: 'Fantastik / Macera',
    originalQuote: 'One does not simply walk into Mordor.',
    fallbackParaphrase: "Entering the enemy's dark realm is not a task easily accomplished on foot.",
    contextHint: "Orta Dünya'nın kaderini belirleyecek bir konseyde dile getirilen tarihi bir uyarı.",
    hints: { character: 'Boromir', actor: 'Sean Bean', director: 'Peter Jackson' },
  },
  {
    id: 'q_016',
    movie: 'Terminator 2: Judgment Day',
    year: 1991,
    genre: 'Bilim Kurgu / Aksiyon',
    originalQuote: 'Hasta la vista, baby.',
    fallbackParaphrase: 'Farewell until our next encounter, young one.',
    contextHint: "Gelecekten gönderilen sibernetik bir koruyucunun 90'lar aksiyonundaki efsaneleşmiş vedası.",
    hints: { character: 'The Terminator', actor: 'Arnold Schwarzenegger', director: 'James Cameron' },
  },
  {
    id: 'q_017',
    movie: 'Titanic',
    year: 1997,
    genre: 'Romantik / Drama',
    originalQuote: "I'm the king of the world!",
    fallbackParaphrase: 'I hold absolute reign over the entire planet!',
    contextHint: 'Tarihi bir deniz felaketinin gölgesinde yeşeren tutkulu bir sınıf farkı aşkı.',
    hints: { character: 'Jack Dawson', actor: 'Leonardo DiCaprio', director: 'James Cameron' },
  },
  {
    id: 'q_018',
    movie: 'A Few Good Men',
    year: 1992,
    genre: 'Drama / Mahkeme',
    originalQuote: "You can't handle the truth!",
    fallbackParaphrase: 'The reality is something you are completely incapable of accepting!',
    contextHint: "Askeri bir mahkemede yüksek rütbeli bir subayın sorgulandığı gerilim dolu 90'lar draması.",
    hints: { character: 'Col. Nathan R. Jessep', actor: 'Jack Nicholson', director: 'Rob Reiner' },
  },
  {
    id: 'q_019',
    movie: 'Jaws',
    year: 1975,
    genre: 'Gerilim / Macera',
    originalQuote: "You're gonna need a bigger boat.",
    fallbackParaphrase: 'It will be necessary for us to procure a vessel of significantly larger proportions.',
    contextHint: 'Bir sahil kasabasında dehşet saçan devasa bir yırtıcıyla yüzleşen ekibin şaşkınlığı.',
    hints: { character: 'Martin Brody', actor: 'Roy Scheider', director: 'Steven Spielberg' },
  },
  {
    id: 'q_020',
    movie: 'Gladiator',
    year: 2000,
    genre: 'Aksiyon / Tarih',
    originalQuote: 'Are you not entertained?',
    fallbackParaphrase: 'Does this spectacle fail to provide you with adequate amusement?',
    contextHint: "Roma İmparatorluğu döneminde ihanete uğrayan bir generalin arenadaki öfke haykırışı.",
    hints: { character: 'Maximus', actor: 'Russell Crowe', director: 'Ridley Scott' },
  },
  {
    id: 'q_021',
    movie: 'Psycho',
    year: 1960,
    genre: 'Korku / Psikolojik Gerilim',
    originalQuote: "A boy's best friend is his mother.",
    fallbackParaphrase: 'A young man\'s most trusted companion is always the woman who raised him.',
    contextHint: 'Sapa bir yol üstü motelinde işlenen cinayetleri konu alan psikolojik siyah-beyaz gerilim.',
    hints: { character: 'Norman Bates', actor: 'Anthony Perkins', director: 'Alfred Hitchcock' },
  },
  {
    id: 'q_022',
    movie: 'Goodfellas',
    year: 1990,
    genre: 'Suç / Drama',
    originalQuote: 'Funny how? Like I\'m a clown, I amuse you?',
    fallbackParaphrase: 'In what manner am I humorous? Do I resemble a performer meant for your entertainment?',
    contextHint: "90'lar mafya sinemasının zirvelerinden; masadaki küçük bir şakanın anında gerilime dönüştüğü an.",
    hints: { character: 'Tommy DeVito', actor: 'Joe Pesci', director: 'Martin Scorsese' },
  },
  {
    id: 'q_023',
    movie: 'Apocalypse Now',
    year: 1979,
    genre: 'Savaş / Drama',
    originalQuote: 'I love the smell of napalm in the morning.',
    fallbackParaphrase: 'The aroma of combustion fuels at daybreak brings me great satisfaction.',
    contextHint: "Vietnam Savaşı'nın yıkımını ve insan zihninin karanlığını konu alan psikolojik savaş filmi.",
    hints: { character: 'Lt. Col. Bill Kilgore', actor: 'Robert Duvall', director: 'Francis Ford Coppola' },
  },
  {
    id: 'q_024',
    movie: 'Back to the Future',
    year: 1985,
    genre: 'Bilim Kurgu / Komedi',
    originalQuote: "Roads? Where we're going, we don't need roads.",
    fallbackParaphrase: 'Paved pathways? The destination we are heading toward requires no infrastructure.',
    contextHint: "Zaman yolculuğu yapan bir araba ve eksantrik bir bilim insanının 80'ler macerası.",
    hints: { character: 'Dr. Emmett Brown', actor: 'Christopher Lloyd', director: 'Robert Zemeckis' },
  },
  {
    id: 'q_025',
    movie: 'Gone with the Wind',
    year: 1939,
    genre: 'Romantik / Tarih',
    originalQuote: "Frankly, my dear, I don't give a damn.",
    fallbackParaphrase: 'To be entirely honest, my beloved, I care very little about the matter.',
    contextHint: 'Amerikan İç Savaşı zemininde geçen destansı bir aşk ve gurur hikayesi.',
    hints: { character: 'Rhett Butler', actor: 'Clark Gable', director: 'Victor Fleming' },
  },
  {
    id: 'q_026',
    movie: 'The Social Network',
    year: 2010,
    genre: 'Biyografi / Drama',
    originalQuote: "A million dollars isn't cool. You know what's cool? A billion dollars.",
    fallbackParaphrase: 'Seven figures lacks prestige. Do you realize what carries true weight? Ten figures.',
    contextHint: "2000'lerin başında bir yurt odasında kurulan dijital bir imparatorluğun hırslı kuruluş öyküsü.",
    hints: { character: 'Sean Parker', actor: 'Justin Timberlake', director: 'David Fincher' },
  },
  {
    id: 'q_027',
    movie: 'Whiplash',
    year: 2014,
    genre: 'Drama / Müzik',
    originalQuote: "There are no two words in the English language more harmful than 'good job'.",
    fallbackParaphrase: 'No pair of terms in human speech causes more detriment than satisfactory praise.',
    contextHint: 'Mükemmelliyetçi bir caz eğitmeni ile genç bir davulcu arasındaki acımasız psikolojik savaş.',
    hints: { character: 'Terrence Fletcher', actor: 'J.K. Simmons', director: 'Damien Chazelle' },
  },
  {
    id: 'q_028',
    movie: 'Interstellar',
    year: 2014,
    genre: 'Bilim Kurgu / Drama',
    originalQuote: 'Mankind was born on Earth. It was never meant to die here.',
    fallbackParaphrase: 'Humanity originated on this planet, yet it was never destined for total extinction here.',
    contextHint: "Tükenmekte olan Dünya'yı kurtarmak için solucan deliğinden geçen astronotların uzay yolculuğu.",
    hints: { character: 'Cooper', actor: 'Matthew McConaughey', director: 'Christopher Nolan' },
  },
  {
    id: 'q_029',
    movie: 'No Country for Old Men',
    year: 2007,
    genre: 'Suç / Gerilim',
    originalQuote: "What's the most you ever lost on a coin toss?",
    fallbackParaphrase: 'What represents the highest stake you have ever forfeited based on a random flip?',
    contextHint: 'Teksas kırsalında kayıp bir para çantasının peşine düşen acımasız bir kiralık katilin gerilimi.',
    hints: { character: 'Anton Chigurh', actor: 'Javier Bardem', director: 'Joel & Ethan Coen' },
  },
  {
    id: 'q_030',
    movie: 'Inglourious Basterds',
    year: 2009,
    genre: 'Savaş / Drama',
    originalQuote: 'Au revoir, Shoshanna!',
    fallbackParaphrase: 'Farewell until we meet again, my dear young lady!',
    contextHint: "2. Dünya Savaşı Fransa'sında kurnaz bir Nazi subayının kaçan bir kızı izlerken attığı nida.",
    hints: { character: 'Col. Hans Landa', actor: 'Christoph Waltz', director: 'Quentin Tarantino' },
  },
  {
    id: 'q_031',
    movie: 'Oppenheimer',
    year: 2023,
    genre: 'Biyografi / Drama',
    originalQuote: 'Now I am become Death, the destroyer of worlds.',
    fallbackParaphrase: 'At this moment, I have transformed into ultimate mortality, the annihilator of realms.',
    contextHint: 'Atom bombasının geliştirilme sürecini ve vicdani hesaplaşmasını konu alan tarihi biyografi.',
    hints: { character: 'J. Robert Oppenheimer', actor: 'Cillian Murphy', director: 'Christopher Nolan' },
  },
  {
    id: 'q_032',
    movie: 'Joker',
    year: 2019,
    genre: 'Psikolojik Gerilim / Drama',
    originalQuote: "I used to think that my life was a tragedy, but now I realize, it's a comedy.",
    fallbackParaphrase: 'I previously perceived my existence as a misfortune, yet I now comprehend its humorous nature.',
    contextHint: 'Toplum tarafından dışlanan başarısız bir komedyenin kaos sembolüne dönüşme hikayesi.',
    hints: { character: 'Arthur Fleck', actor: 'Joaquin Phoenix', director: 'Todd Phillips' },
  },
  {
    id: 'q_033',
    movie: 'The Truman Show',
    year: 1998,
    genre: 'Bilim Kurgu / Drama',
    originalQuote: "In case I don't see ya, good afternoon, good evening, and good night!",
    fallbackParaphrase: 'Lest our paths fail to cross again today, warm wishes for the remaining hours of your cycle!',
    contextHint: "Tüm hayatının devasa bir televizyon seti ve şovdan ibaret olduğunu anlayan bir adamın ikonik selamı.",
    hints: { character: 'Truman Burbank', actor: 'Jim Carrey', director: 'Peter Weir' },
  },
  {
    id: 'q_034',
    movie: 'Dead Poets Society',
    year: 1989,
    genre: 'Drama',
    originalQuote: 'Oh Captain! My Captain!',
    fallbackParaphrase: 'Salutations to our leader and respected guide!',
    contextHint: 'Disiplinli bir erkek yatılı okulunda öğrencilerine edebiyatı ve özgür düşünceyi aşılayan bir öğretmen.',
    hints: { character: 'John Keating', actor: 'Robin Williams', director: 'Peter Weir' },
  },
  {
    id: 'q_035',
    movie: 'The Matrix',
    year: 1999,
    genre: 'Bilim Kurgu',
    originalQuote: 'I know kung fu.',
    fallbackParaphrase: 'I have mastered martial arts through direct data transmission.',
    contextHint: 'Zihnine saniyeler içinde dövüş sanatı verileri yüklenen bir seçilmiş kişinin şaşkınlık dolu tespiti.',
    hints: { character: 'Neo', actor: 'Keanu Reeves', director: 'Lana & Lilly Wachowski' },
  },
  {
    id: 'q_036',
    movie: 'Braveheart',
    year: 1995,
    genre: 'Biyografi / Tarih',
    originalQuote: "They may take our lives, but they'll never take our freedom!",
    fallbackParaphrase: 'They possess the power to end our existence, yet our liberty remains forever beyond their reach!',
    contextHint: "İskoçya'nın bağımsızlığı için İngiliz kraliyetine karşı ordularını toplayan bir halk kahramanının tiradı.",
    hints: { character: 'William Wallace', actor: 'Mel Gibson', director: 'Mel Gibson' },
  },
  {
    id: 'q_037',
    movie: 'Wall Street',
    year: 1987,
    genre: 'Drama / Suç',
    originalQuote: 'Greed, for lack of a better word, is good.',
    fallbackParaphrase: 'Excessive desire, in the absence of a more precise descriptor, serves a beneficial purpose.',
    contextHint: "80'lerin borsa dünyasında hırs ve finansal manipülasyonları öven acımasız bir yatırımcının söylevi.",
    hints: { character: 'Gordon Gekko', actor: 'Michael Douglas', director: 'Oliver Stone' },
  },
  {
    id: 'q_038',
    movie: 'The Prestige',
    year: 2006,
    genre: 'Drama / Gizem',
    originalQuote: 'Every magic trick consists of three parts or acts.',
    fallbackParaphrase: 'All illusions presented to an audience are structured across three distinct phases.',
    contextHint: "19. yüzyıl sonu Londra'sında rekabet eden iki sihirbazın takıntı ve sırlarla dolu mücadelesi.",
    hints: { character: 'Cutter', actor: 'Michael Caine', director: 'Christopher Nolan' },
  },
  {
    id: 'q_039',
    movie: 'Se7en',
    year: 1995,
    genre: 'Suç / Gizem',
    originalQuote: "What's in the box?",
    fallbackParaphrase: 'What item has been placed inside this enclosed container?',
    contextHint: "Yedi ölümcül günahı işleyen bir seri katilin peşindeki dedektiflerin çöl ortasındaki şok edici finali.",
    hints: { character: 'David Mills', actor: 'Brad Pitt', director: 'David Fincher' },
  },
  {
    id: 'q_040',
    movie: 'V for Vendetta',
    year: 2005,
    genre: 'Aksiyon / Drama',
    originalQuote: 'People should not be afraid of their governments. Governments should be afraid of their people.',
    fallbackParaphrase: 'Citizens ought not to dread their ruling authorities; rather, the leadership should fear the populace.',
    contextHint: 'Baskıcı ve totaliter bir gelecekte maskeli bir özgürlük savaşçısının devrim çağrısı.',
    hints: { character: 'V', actor: 'Hugo Weaving', director: 'James McTeigue' },
  },
  {
    id: 'q_041',
    movie: 'Alien',
    year: 1979,
    genre: 'Korku / Bilim Kurgu',
    originalQuote: 'In space no one can hear you scream.',
    fallbackParaphrase: 'Within the vacuum of the cosmos, auditory distress signals remain entirely unperceived.',
    contextHint: 'Ticari bir uzay gemisi mürettebatının bilinmeyen bir yaratıkla kapalı alandaki hayatta kalma mücadelesi.',
    hints: { character: 'Tagline / İkonik Cümle', actor: 'Sigourney Weaver (Başrol)', director: 'Ridley Scott' },
  },
  {
    id: 'q_042',
    movie: 'The Big Lebowski',
    year: 1998,
    genre: 'Komedi / Suç',
    originalQuote: 'The Dude abides.',
    fallbackParaphrase: 'The relaxed individual simply persists through all circumstances.',
    contextHint: 'Kendi halinde bir kase oyuncusunun yanlış anlaşılmalar sonucu karıştığı saçma mafya olayları.',
    hints: { character: 'The Dude', actor: 'Jeff Bridges', director: 'Joel & Ethan Coen' },
  },
  {
    id: 'q_043',
    movie: 'Jerry Maguire',
    year: 1996,
    genre: 'Drama / Romantik',
    originalQuote: 'Show me the money!',
    fallbackParaphrase: 'Demonstrate to me the financial compensation!',
    contextHint: "Kendi ajansını kuran bir spor menajerinin hırslı sporcusuyla telefonda bağırdığı 90'lar klasiği.",
    hints: { character: 'Rod Tidwell', actor: 'Cuba Gooding Jr.', director: 'Cameron Crowe' },
  },
  {
    id: 'q_044',
    movie: 'Apollo 13',
    year: 1995,
    genre: 'Biyografi / Drama',
    originalQuote: 'Houston, we have a problem.',
    fallbackParaphrase: 'Mission Control, a complication has arisen on our vessel.',
    contextHint: 'Uzay görevi sırasında patlama yaşayan astronot ekibinin merkeze bildirdiği hayati teknik arıza.',
    hints: { character: 'Jim Lovell', actor: 'Tom Hanks', director: 'Ron Howard' },
  },
  {
    id: 'q_045',
    movie: 'Dirty Harry',
    year: 1971,
    genre: 'Aksiyon / Suç',
    originalQuote: 'Do I feel lucky? Well, do ya, punk?',
    fallbackParaphrase: 'Am I experiencing good fortune today? Tell me, do you feel fortunate yourself, adversary?',
    contextHint: "Kural tanımaz bir polisin silahındaki son mermiyi sorgulatarak suçluyu tehdit ettiği 70'ler aksiyonu.",
    hints: { character: 'Harry Callahan', actor: 'Clint Eastwood', director: 'Don Siegel' },
  },
  {
    id: 'q_046',
    movie: 'Spiderman',
    year: 2002,
    genre: 'Aksiyon / Çizgi Roman',
    originalQuote: 'With great power comes great responsibility.',
    fallbackParaphrase: 'Immense capability inevitably demands a corresponding level of duty.',
    contextHint: 'Sıradan bir gencin süper güçler kazandıktan sonra amcasından aldığı hayat dersi.',
    hints: { character: 'Uncle Ben', actor: 'Cliff Robertson', director: 'Sam Raimi' },
  },
  {
    id: 'q_047',
    movie: 'Mean Girls',
    year: 2004,
    genre: 'Komedi / Gençlik',
    originalQuote: 'On Wednesdays we wear pink.',
    fallbackParaphrase: 'Midweek dictates our mandatory adoption of magenta-toned attire.',
    contextHint: "2000'ler lise hiyerarşisinde popüler kız grubunun katı giyim kurallarından biri.",
    hints: { character: 'Karen Smith', actor: 'Amanda Seyfried', director: 'Mark Waters' },
  },
  {
    id: 'q_048',
    movie: 'The Wolf of Wall Street',
    year: 2013,
    genre: 'Biyografi / Suç',
    originalQuote: 'Sell me this pen.',
    fallbackParaphrase: 'Convince me to purchase this writing utensil.',
    contextHint: 'Yasadışı yöntemlerle servet kazanan bir borsa simsarının ikna yeteneğini sınamak için sorduğu soru.',
    hints: { character: 'Jordan Belfort', actor: 'Leonardo DiCaprio', director: 'Martin Scorsese' },
  },
  {
    id: 'q_049',
    movie: 'Inception',
    year: 2010,
    genre: 'Bilim Kurgu / Aksiyon',
    originalQuote: 'An idea is like a virus. Resilient. Highly contagious.',
    fallbackParaphrase: 'A thought functions similarly to a pathogen. Enduring. Rapidly transmissible.',
    contextHint: 'İnsanların rüyalarına girerek bilgi çalan uzmanın, zihne fikir ekme üzerine yaptığı analiz.',
    hints: { character: 'Dom Cobb', actor: 'Leonardo DiCaprio', director: 'Christopher Nolan' },
  },
  {
    id: 'q_050',
    movie: '12 Angry Men',
    year: 1957,
    genre: 'Drama / Mahkeme',
    originalQuote: "It's always tough to keep personal prejudice out of a thing like this.",
    fallbackParaphrase: 'Excluding individual bias from a verdict of such gravity is invariably challenging.',
    contextHint: 'Bir cinayet davasında idam kararını tartışan 12 jüri üyesinin kapalı odadaki vicdan mücadelesi.',
    hints: { character: 'Juror 8', actor: 'Henry Fonda', director: 'Sidney Lumet' },
  },
];
